# Generated by Django 2.2.5 on 2019-11-04 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField(verbose_name='ユーザー')),
                ('user_view', models.IntegerField(verbose_name='閲覧数')),
                ('user_date', models.DateField(verbose_name='日付')),
            ],
        ),
    ]
