# Generated by Django 2.2.5 on 2019-11-04 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_webdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webdata',
            name='user_date',
        ),
    ]
