# Generated by Django 2.2.5 on 2019-11-04 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_remove_webdata_user_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
    ]
