# Generated by Django 2.2.5 on 2020-08-08 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_auto_20200727_1146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GoDate',
        ),
        migrations.DeleteModel(
            name='WebData',
        ),
    ]
