# Generated by Django 2.2.5 on 2020-08-08 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20200808_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_data', models.DateField(verbose_name='年月')),
                ('access_data', models.IntegerField(verbose_name='アクセス数')),
            ],
        ),
    ]
