# Generated by Django 2.2.5 on 2021-03-27 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_googleaccess'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='googleaccess',
            options={'verbose_name': 'グーグルアクセスデータリスト', 'verbose_name_plural': 'グーグルアクセスデータリスト'},
        ),
        migrations.AlterModelOptions(
            name='popular',
            options={'verbose_name': '人気記事リスト', 'verbose_name_plural': '人気記事リスト'},
        ),
    ]
